language: c
services: docker
sudo: required
script:
  - make build
after_script:
  - docker images
deploy:
  - provider: script
    script: make docker-deploy
    on:
      branch:
        - master
        - develop
        - docker-devel
notifications:
  email:
    on_success: never
    on_failure: change
